---   ### This playbook is to delete security group


- hosts: tag_Name_Master_1
  connection: local
  gather_facts: no
#  user: ubuntu
  vars_files:
    - group_vars/all
  roles:
    - create_users

