---

# Create Users

- name: Create User
  shell: oc create user sahid

- name: Create Password
  shell: htpasswd -b /etc/origin/master/htpasswd sahid {{ oc_user_pw }}
  become: sudo

- name: Grant Sahid User Admin Rights
  shell: oc adm policy add-cluster-role-to-user cluster-admin sahid




